# Array

In [1]:
import numpy as np

In [2]:
# Method 1
np.array([[1,2],[3,4]])


array([[1, 2],
       [3, 4]])

In [4]:
# Method 2
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# Making arrays with specific numbers


In [4]:
# Defining arrays: np.zeros, np.ones, np.full

In [5]:
np.zeros((3,1))


array([[0.],
       [0.],
       [0.]])

In [6]:
np.ones((3, 1))


array([[1.],
       [1.],
       [1.]])

In [5]:
np.full((3,3),10)


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

# Array shape


In [6]:
vector = np.arange(5)
print(vector)
print("Vector shape:", vector.shape)



[0 1 2 3 4]
Vector shape: (5,)


In [7]:
matrix = np.ones([3, 2])
print(matrix)
print("Matrix shape:", matrix.shape)



[[1. 1.]
 [1. 1.]
 [1. 1.]]
Matrix shape: (3, 2)


In [9]:
tensor = np.zeros([3, 3, 3])
print(tensor)
print("Tensor shape:", tensor.shape)

[[[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]
  [0. 0. 0.]]]
Tensor shape: (3, 3, 3)


# Reshaping

In [10]:
arr = np.arange(1, 10)
print(arr, '\n')





[1 2 3 4 5 6 7 8 9] 



In [13]:
# Reshape to 3x3 matrix
arr = arr.reshape(3, 3)
print(arr, '\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 



In [14]:
# Reshape back to the original size
arr = arr.reshape(9)
print(arr)

[1 2 3 4 5 6 7 8 9]
